[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

#upload_protocol = esptool
#upload_port = COM6
upload_protocol = espota
upload_port = SmartCold-5C4774C55494.local

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson
  milesburton/DallasTemperature
  paulstoffregen/OneWire